export const ADD_PHOTOSHOOT_START   = "ADD_PHOTOSHOOT_START";
export const ADD_PHOTOSHOOT_SUCCESS = "ADD_PHOTOSHOOT_SUCCESS";
export const ADD_PHOTOSHOOT_ERROR   = "ADD_PHOTOSHOOT_ERROR";

export const UPDATE_PHOTOSHOOT_START   = "UPDATE_PHOTOSHOOT_START";
export const UPDATE_PHOTOSHOOT_SUCCESS = "UPDATE_PHOTOSHOOT_SUCCESS";
export const UPDATE_PHOTOSHOOT_ERROR   = "UPDATE_PHOTOSHOOT_ERROR";

export const RETRIEVE_ALL_PHOTOSHOOTS_START   = "RETRIEVE_ALL_PHOTOSHOOTS_START";
export const RETRIEVE_ALL_PHOTOSHOOTS_SUCCESS = "RETRIEVE_ALL_PHOTOSHOOTS_SUCCESS";
export const RETRIEVE_ALL_PHOTOSHOOTS_ERROR   = "RETRIEVE_ALL_PHOTOSHOOTS_ERROR";

export const DELETE_PHOTOSHOOT_START   = "DELETE_PHOTOSHOOT_START";
export const DELETE_PHOTOSHOOT_SUCCESS = "DELETE_PHOTOSHOOT_SUCCESS";
export const DELETE_PHOTOSHOOT_ERROR   = "DELETE_PHOTOSHOOT_ERROR";

export const CREATE_ACCOUNT_START   = "CREATE_ACCOUNT_START";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_ERROR   = "CREATE_ACCOUNT_ERROR";

export const LOG_IN_START   = "LOG_IN_START";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR   = "LOG_IN_ERROR";

export const RETRIEVE_REPORT_START = "RETRIEVE_REPORT_START";
export const RETRIEVE_REPORT_SUCCESS = "RETRIEVE_REPORT_SUCCESSS";
export const RETRIEVE_REPORT_ERROR = "RETRIEVE_REPORT_ERROR";

export const CLEAR_LOG_IN_CREATE_ACCOUNT_SERVER_ERROR = "CLEAR_LOG_IN_CREATE_ACCOUNT_SERVER_ERROR";

